### ISSUE TITLE
Review Exeter and PrePress queries to establish priority for Wiki completion

### ISSUE THREAD

**Issue by JGilbert-eLife** [elifesciences/eLife-JATS-schematron#102]

**Comment by bcollins14** [comment]
Feedback from Exeter:

1. How to proceed if Institute ID missing in funding group.

2. When we consider the para as a list

3. How to handle if the figure is cited inside the figure

**Comment by bcollins14** [comment]
Prepress main queries: 

- Table headers “the table row starting “2B” contains a th element (header).”
- table-wrap has more than one table - Is this correct
- decision letter front-stub has only 1 contrib-group element. Is this correct? i.e. were all of the reviewers (aside from the reviwing editor) anonymous
- First contrib-group in decision letter contains a contrib which is not marked up as an editor
- Figure X does not appear directly after the paragraph citing it. Is that correct?
- ... that paragraphs don’t end in punctuation
- X labels do not end in a full stop (figures, AR images, source data files etc)
- X label does not conform to eLife’s usual format
- The <ext-link> element is required. Reference ‘bib23’ has no <ext-link> elements. And similar reference related required warnings/errors.
