### ISSUE TITLE
Create issue template for work on the wiki.

### ISSUE THREAD

**Issue by JGilbert-eLife** [elifesciences/eLife-JATS-schematron#103]
- [x] set up template for creating issues related to wiki writing
- [ ] update template based on the output of #101
- [ ] get team to review proposed template

**Comment by FAtherden-eLife** [comment]
I have [created a wiki page template](https://github.com/elifesciences/eLife-JATS-schematron/issues/new/choose). 

@JGilbert-eLife, @bcollins14, @naushinthomson  Please could you take a look? Does the template DoD look OK? Anything missing which needs to be there by default?

**Comment by JGilbert-eLife** [comment]
Do we want to make it more granular - e.g. have tick boxes for the different sections we want to complete, for adding examples, adding rules etc? Do you think that would be more useful for tracking progress?

**Comment by FAtherden-eLife** [comment]
> Do we want to make it more granular - e.g. have tick boxes for the different sections we want to complete, for adding examples, adding rules etc? Do you think that would be more useful for tracking progress?

Sounds good to me - presume that would mean waiting on #101, so I'll move this back into 'To do'.
