### ISSUE TITLE
Add to paragraph Wiki page queries from #102 and #104

### ISSUE THREAD

**Issue by FAtherden-eLife** [elifesciences/eLife-JATS-schematron#117]
- [x] Add guidance for warnings about paragraphs that don’t end in punctuation
- [ ] Becky reviewed and approved additions?
- [ ] James reviewed and approved additions?
- [ ] Fred reviewed and approved additions?
- [ ] '[Message change](https://github.com/elifesciences/eLife-JATS-schematron/issues/new/choose)' ticket created for Fred to update the Schematron

See paragraph related queries from #102 and #104

**Comment by naushinthomson** [comment]
@FAtherden-eLife @JGilbert-eLife @bcollins14 
I've added to the paragraph page about this warning - please review/approve :)
