### ISSUE TITLE
Check for full stops in names

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/eLife-JATS-schematron#124]
#### Background
I sometimes see initials followed by full stops, especially in editor names

#### Describe what you would like tested
Find full stops in name strings and ask and indicate they should be removed

#### elements affected
<name>

#### Suggested schematron message
There is a full stop present in this name, which is not allowed

#### Suggested role (warning or error)
warning | error | not sure
error?
Can't think of any times it would be OK

#### Stage
pre-edit | final | both
both

#### Example
Article number is fine

**Comment by FAtherden-eLife** [comment]
Should be covered by [`surname-test-4`](https://github.com/elifesciences/eLife-JATS-schematron/blob/4022dacfac35acc4b3e25fd876a2ef34dba6aea3/src/schematron.sch#L1179-L1181), and [`given-names-test-5`](https://github.com/elifesciences/eLife-JATS-schematron/blob/4022dacfac35acc4b3e25fd876a2ef34dba6aea3/src/schematron.sch#L1204-L1206) I think:
`given-names/surname should usually only contain letters, spaces, or hyphens. <value-of select="."/> contains other characters.`

@Melissa37, could you provide an example of where you've seen this and it's not been flagged so I can determine whether it's a bug?

**Comment by Melissa37** [comment]
Probably reviewers - not looking in sub-article for these rules?

**Comment by FAtherden-eLife** [comment]
Able to reproduce with reviewers in `sub-article`s.
