### ISSUE TITLE
Add 'Current rules for brackets around references' to citations page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/eLife-JATS-schematron#125]
- [x] Check features are ok with change
- [ ] Create citations page
- [ ] Current rules for brackets added
- [ ] Team reviewed and approved page?
- [ ] '[Message change](https://github.com/elifesciences/eLife-JATS-schematron/issues/new/choose)' ticket created for Fred to update the Schematron
- [ ] Update copyeditor house style document and let them know
- [ ] Feed back to Exeter about change

**Comment by Melissa37** [comment]
@naushinthomson I don't think this topic needs its own page does it? Will it be a part of the generic citations page?

**Comment by naushinthomson** [comment]
@Melissa37 Fair enough, I've changed it now!

**Comment by JGilbert-eLife** [comment]
I've updated https://docs.google.com/document/d/1MSTDqaGtaZYA4FL5j4yv_Mv0BsyGZyYMO-QtcggpMJc/edit# to account for the changes to the style we have discussed. I'm ready to start on the page following the discussion next week.

**Comment by JGilbert-eLife** [comment]
I would probably also have to wait for the schematron rules to be updated (or at least for https://docs.google.com/spreadsheets/d/1GtNMufkcNoYz3zfYJVXfxl2MyqhYosDuPdIoXN1dPp8/edit#gid=0 to be updated to match the latest rules!)

**Comment by FAtherden-eLife** [comment]
@JGilbert-eLife  I've updated the pertinent section in that spreadsheet (rows 840-856) with the rules in branch `ref-cite-changes`.
