### ISSUE TITLE
Scope out whole project

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/eLife-JATS-schematron#126]
- [x] Create a template for issues to be created using
- [ ] Ensure there is an issue created for every area of the project - including "other topics" that don't fit in directly but are part of protocols and house style documentation
- [ ] Put the issues into Milestones in order to estimate the length of the project

Suggested tick boxes for issue template:

- [ ] Create Wiki page 
- [ ] Populate Wiki with content from current protocols document
- [ ] Populate Wiki with schematron messages and provide good and bad examples
- [ ] Provide explanations for how to fix schematron errors and warnings
- [ ] Review house style document to ensure all requirements are covered by Wiki, and schematron
- [ ] Review Schematron messages related to this topic to ensure they are user friendly
- [ ] Review feedback from Exeter to check this is covered in the Wiki
- [ ] Review new starter feedback to check this is covered in the Wiki
- [ ] Review Prepress projects feedback to check this is covered in the Wiki
- [ ] Review all above - is it all necessary? How fussy are we being?

- [ ] eLife production team approved Wiki page
- [ ] Exeter production team approved Wiki page
- [ ] Wiki page completed

- [ ] '[Message change](https://github.com/elifesciences/eLife-JATS-schematron/issues/new/choose)' ticket created for Fred to update the Schematron

**Comment by Melissa37** [comment]
HI @naushinthomson I updated this ticket a bit - is that OK? I am not sure whether I have added to the purpose of this ticket or changed it's meaning (sorry if the latter!!)
