### ISSUE TITLE
Create Schematron spreadsheet

### ISSUE THREAD

**Issue by FAtherden-eLife** [elifesciences/eLife-JATS-schematron#131]
Create spreadsheet containing, ID, context, and message for every test in the Schematron.
- [ ] update spreadsheet with latest schematron messages

**Comment by FAtherden-eLife** [comment]
Spreadsheet: https://docs.google.com/spreadsheets/d/1GtNMufkcNoYz3zfYJVXfxl2MyqhYosDuPdIoXN1dPp8/edit#gid=0

@JGilbert-eLife, @naushinthomson, @bcollins14 - could you take a look and see if this would be helpful?

**Comment by naushinthomson** [comment]
Looks good to me!

**Comment by JGilbert-eLife** [comment]
It looks good to me too, though I wonder if we need to group the messages more? How easy would that be?

**Comment by bcollins14** [comment]
Looks good to me too.

**Comment by FAtherden-eLife** [comment]
Do I still need to do this (attempt to group the messages) given what we discussed in the meeting?
