### ISSUE TITLE
Update Schematron to account for 1 reference citation style

### ISSUE THREAD

**Issue by FAtherden-eLife** [elifesciences/eLife-JATS-schematron#152]
Currently eLife allow two citation styles for references, Smith et al., 2020 and Smith et al. (2020).

We want to simplify this to allow 1 style - Smith et al., 2020.

All the rules need updating to account for this change in policy.

**Comment by FAtherden-eLife** [comment]
@JGilbert-eLife, @Melissa37, do we want to allow `Smith et al. (2020)`, but not actively pursue it, or only allow `Smith et al., 2020`?

i.e. If any author changes `Smith et al., 2020` to `Smith et al. (2020)` during proofing, is the expected result at PAV/Pub Review an error firing?

**Comment by FAtherden-eLife** [comment]
Assume based on [this comment](https://github.com/elifesciences/eLife-JATS-schematron/issues/146#issuecomment-582857907) that its the former?

**Comment by FAtherden-eLife** [comment]
[Published branch](https://github.com/elifesciences/eLife-JATS-schematron/tree/ref-cite-changes)
Assuming the above assumptions are correct, then this is is OK to merge when Exeter have been informed and the new validator is running.

**Comment by Melissa37** [comment]
>@JGilbert-eLife, @Melissa37, do we want to allow Smith et al. (2020), but not actively pursue it, or only allow Smith et al., 2020?
>i.e. If any author changes Smith et al., 2020 to Smith et al. (2020) during proofing, is the expected result at PAV/Pub Review an error firing?

If the author changes it during proofing that's fine, but it should be consistently Smith et al., 2020 when it comes out of pre-editing.

**Comment by FAtherden-eLife** [comment]
@Melissa37, @JGilbert-eLife, do we still want checks to determine whether brackets should be around the reference or not?

I.e. a warning for something like:
> ... as report in (**Smith et al., 1992**), we used ...

**Comment by JGilbert-eLife** [comment]
Yes, I think so. We still wouldn't want citations that are part of a sentence to be bracketed.

**Comment by Melissa37** [comment]
Agreed with James

**Comment by FAtherden-eLife** [comment]
Thanks. Changes made in latest commit to `ref-cite-changes`. Will merge once the validator has been deployed and integrated int the Kriya workflow.

**Comment by FAtherden-eLife** [comment]
I am able to merge this whenever now that the new validator is up and running and can be redeployed at any time. Presume we need to inform Exeter and update the documentation first?
