### ISSUE TITLE
Feature: Query Crossref api for dois of references w/o dois

### ISSUE THREAD

**Issue by fred-atherden** [elifesciences/eLife-JATS-schematron#160]
Leverage BaseX Rest api to query [Crossref's API](https://github.com/CrossRef/rest-api-doc) for references without dois.

Example could be to do:
```xquery
http:send-request(<http:request method='get' href="{('https://api.crossref.org/works?rows=3&amp;query.bibliographic='||$title-query||'&amp;mailto=f.atherden@elifesciences.org')}" timeout='2'><http:header name="User-Agent" value="f.atherden@elifesciences.org"/></http:request>)
```
where `$title-query` is the title of a reference without a doi. 

The JSON result(s) could be compared against the original using [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) in order to determine likelihood of a match.

**Comment by FAtherden-eLife** [comment]
pre-existing [basex-validator-docker](https://github.com/elifesciences/basex-validator-docker) could be used.

This could be UI'd as a page the user uploads an XML document to. The user could be presented with the (enriched, i.e. likelihood defined) result.

**Comment by FAtherden-eLife** [comment]
From Crossref documentation:
> Specifically, we encourage the following polite behaviour:
> Cache data so you don't request the same data over and over again.

Correct matches could be input into a BaseX database, and this could be queried prior to the Crossref API.
