### ISSUE TITLE
Search for + /- and suggest changing to ±

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/eLife-JATS-schematron#85]
#### Suggested role (warning or error)
warning | error | not sure

#### Stage
pre-edit | final | both

#### Example
Article number is fine

**Comment by FAtherden-eLife** [comment]
@Melissa37, @JGilbert-eLife  
Noting that the spacing is incorrect - `+ /-`.

Examples of legit uses of  `+/-` and `-/-` in https://elifesciences.org/articles/51447/figures#supp1 as an example.
<img width="750" alt="Screen Shot 2019-12-20 at 10 52 55" src="https://user-images.githubusercontent.com/43879983/71250269-2c240700-2317-11ea-8f3c-2b08ba77ff40.png">


Should we change this to check the spacing? `+ /-` to `+/-` and similar?
