### ISSUE TITLE
Highlighting References we expect to have DOIs

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/eLife-JATS-schematron#92]
References without DOIs that have them Code searches Crossref or PubMed. If not there go to PubMed or the journal website itself. Melissa to ask Fred to identify refs without DOIs using a Schematron rule - exclude web/software references/known journals without DOIs or DOIs before a certain date. Some books now have DOIs so can be checked - publishers who do known DOIs for books should be checked. Melissa to talk to Fred

#### Background
Currently Exeter have probe rules that indicate when a reference does not have a DOI and they also display a red line by the side of the Ref if it does not have a DOI.
Exeter ignore these as many are known to not have a DOI.

#### Describe what you would like tested
To ensure the right references are checked if a DOI is missing and lots of false positives are not thrown up, I'd like to have a test that identifies references that do ot have a DOI and sre not ref-type "web" or any others we know never have a DOI.
AND these criteria:

- If they don't have a DOI to check whether they are known journals that don't have DOIs (@JGilbert-eLife can provide this information)
- If the date of the reference precedes a date a known journal started assigning DOIs (I think @JGilbert-eLife can provide this information)
- If the publisher is known to give books DOIs and if so when they started doing this  (I think this can be found by using the Crossref metadata search for books/book chapters)
- If a software reference and NOT Figshare ignore
- If data and not X, Y or Z, ignore.

#### Suggested schematron message
This reference might have a DOI that is missing, please check

#### Suggested role (warning or error)
warning

#### Stage
pre-edit | final | both

#### Example
Article number is fine

**Comment by FAtherden-eLife** [comment]
@JGilbert-eLife, could you provide the information @Melissa37 mentions above (or comment on this) before I start this?

**Comment by JGilbert-eLife** [comment]
You want this: https://github.com/elifesciences/reference-schematron/blob/master/journal-DOI.xml

**Comment by FAtherden-eLife** [comment]
Crossref have a report containing all registered journals - https://www.crossref.org/xref/xml/mddb.xml

This is an XML file containing info on each journal, for example:
`<journal title="eLife" abbr="" issn="|2050084X" years="2012-0" volumes="1-9" prefix="10.7554"/>`

Problem is that there are 74k+ entries, so too many to simple include or invoke in one (or many tests). I think we might have to be selective (especially given the [current memory issues](https://github.com/elifesciences/jats-validator-docker/issues/3))...

**Comment by Melissa37** [comment]
https://search.crossref.org/?q=books&type-name=Book

This lists the publishers who assign DOIs to books - not all their portfolio by the looks of it!

https://search.crossref.org/?q=chapter&type-name=Chapter

This lists the publishers assigning chapters DOIs. 

I would use these as keywords in the publisher tag for whether we should look for a DOI, but remembering Springer is more likely to be in our XML than Springer international publishing or  Springer Berlin Heidelberg

**Comment by Melissa37** [comment]
@FAtherden-eLife 
>Crossref have a report containing all registered journals - https://www.crossref.org/xref/xml/mddb.xml

Yes, think we should stick to our known ones!

**Comment by FAtherden-eLife** [comment]
>> @FAtherden-eLife
>> Crossref have a report containing all registered journals - https://www.crossref.org/xref/xml/mddb.xml

> Yes, think we should stick to our known ones!

OK, looks like 5,316 have exact matches in our archive, so let's try first with those and see if that slows things down so much that we have to be more selective.

**Comment by FAtherden-eLife** [comment]
Simple implementation for journals and books in PR https://github.com/elifesciences/eLife-JATS-schematron/pull/98.

Files of importance are:
- [Journal list](https://github.com/elifesciences/eLife-JATS-schematron/blob/52d542b291342633e21d8b2f2a19275f08a255e9/src/journals.xml)
Logic flags missing DOIs unless the journal title is in the above list and the year is equal to or greater than the respective year. 
- [Publisher list](https://github.com/elifesciences/eLife-JATS-schematron/blob/52d542b291342633e21d8b2f2a19275f08a255e9/src/publishers.xml)
Logic is simpler here - if a book ref has no DOI and the publisher name is the same as one in this list, then a warning is flagged

**Comment by FAtherden-eLife** [comment]
Added another commit containing software checks in the above PR. 

Now for conference proceedings.
